import { Montserrat } from "next/font/google";
import localFont from 'next/font/local'
import "./globals.css";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"]
})
const superbubble = localFont({
  src: '../../public/fonts/super_bubble/Super-Bubble.ttf',
  variable: '--font-superbubble',
})
const tropicaltides = localFont({
  src: '../../public/fonts/tropical_tides/Tropical-Tides.otf',
  variable: '--font-tropicaltides',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${superbubble.variable} ${tropicaltides.variable} font-montserrat antialiased bg-[#E5FCFF]`}
      >
        {children}
      </body>
    </html>
  );
}
